# Generated by Django 3.0.8 on 2020-07-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
                ('profileName', models.CharField(max_length=150)),
                ('helpfulness', models.CharField(max_length=5)),
                ('score', models.FloatField()),
                ('time', models.DateTimeField()),
                ('summary', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=500)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.products')),
            ],
        ),
    ]
