# Generated by Django 3.0.8 on 2020-07-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200723_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.FloatField(),
        ),
    ]
